# syntax=docker/dockerfile:1.4

# Build stage for the main application
FROM python:3.10-alpine AS builder

WORKDIR /app

COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . .

# Install binutils (required for PyInstaller on Linux)
RUN apk update && apk add binutils

# Install PyInstaller
RUN pip install pyinstaller

# Build the binary
RUN pyinstaller --onefile hello_world.py

# Create a new stage for the development environment
FROM scratch

# WORKDIR /app
# Copy the binary from the previous build stage
COPY --from=builder /app/dist/hello_world /app

# Indicates the ports on which a container listens for connections
EXPOSE 8050

# Set the command to run your binary
CMD ["/app"]