# syntax=docker/dockerfile:1.4

# Build stage for the main application
FROM python:3.10-alpine AS builder

WORKDIR /app

COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python", "hello_world.py"]

# Create a new stage for the development environment
FROM builder as dev-envs

RUN <<EOF
apk update
apk add git bash
EOF

RUN <<EOF
addgroup -S webservice
adduser -S --shell /bin/bash --ingroup webservice webservice
EOF

# Install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /

USER webservice

# Indicates the ports on which a container listens for connections
EXPOSE 8050
